### ISSUE TITLE
 league/flysystem-aws-s3-v3  需要 league/flysystem 2.0  

### ISSUE THREAD

**Issue by xinxin-qian** [hyperf/filesystem#2]
league/flysystem-aws-s3-v3  需要 league/flysystem 2.0  
而这个安装包里面版本是1.1

  Problem 1
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.0
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.0-RC1
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.0-beta.3
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.0-beta.2
    - league/flysystem-aws-s3-v3 2.0.0-alpha.4 requires league/flysystem 2.0.0-alpha.3 -> satisfiable by league/flysystem[2.0.0-alpha.3].
    - league/flysystem-aws-s3-v3 2.0.0-beta.1 requires league/flysystem 2.0.0-alpha.3 -> satisfiable by league/flysystem[2.0.0-alpha.3].
    - Conclusion: don't install league/flysystem 2.0.0-alpha.3
    - Installation request for hyperf/filesystem (locked at v2.0.11, required as ^2.0) -> satisfiable by hyperf/filesystem[v2.0.11].
    - league/flysystem-aws-s3-v3 2.0.0-alpha.1 requires league/flysystem 2.0.0-alpha.1 -> satisfiable by league/flysystem[2.0.0-alpha.1].
    - league/flysystem-aws-s3-v3 2.0.0-alpha.2 requires league/flysystem 2.0.0-alpha.1 -> satisfiable by league/flysystem[2.0.0-alpha.1].
    - Conclusion: don't install league/flysystem 2.0.0-alpha.1
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.x-dev|remove league/flysystem 1.1.3|install league/flysystem 2.0.0-alpha.1|install league/flysystem 2.0.0-alpha.3
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.x-dev|don't install league/flysystem 1.1.3|install league/flysystem 2.0.0-alpha.1|install league/flysystem 2.0.0-alpha.3
    - Installation request for league/flysystem-aws-s3-v3 ^2.0 -> satisfiable by league/flysystem-aws-s3-v3[2.0.0, 2.0.0-RC1, 2.0.0-alpha.1, 2.0.0-alpha.2, 2.0.0-alpha.4, 2.0.0-beta.1, 2.0.0-beta.2, 2.0.0-beta.3, 2.x-dev].
    - league/flysystem-aws-s3-v3 2.x-dev requires league/flysystem ^2.0.0 -> satisfiable by league/flysystem[2.0.0, 2.0.0-RC1, 2.0.0-alpha.1, 2.0.0-alpha.2, 2.0.0-alpha.3, 2.0.0-alpha.4, 2.0.0-beta.1, 2.0.0-beta.2, 2.0.0-beta.3, 2.x-dev].
    - Can only install one of: league/flysystem[2.0.0, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-RC1, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-alpha.2, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-alpha.4, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-beta.1, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-beta.2, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-beta.3, 1.1.3].
    - Can only install one of: league/flysystem[2.x-dev, 1.1.3].
    - Installation request for league/flysystem (locked at 1.1.3) -> satisfiable by league/flysystem[1.1.3].
    
    
    目前是不是支持2.0一下？

**Comment by limingxinleo** [comment]
2.1版本支持了
