### ISSUE TITLE
Class 'League\Flysystem\Adapter\Local' not found

### ISSUE THREAD

**Issue by yangzming** [hyperf/filesystem#3]
这里的适配器压根就不能玩呀
"hyperf/filesystem": "^2.1",
"league/flysystem": "^2.0"

![image](https://user-images.githubusercontent.com/16712383/116524431-f418d500-a909-11eb-9b53-45a4da0092b1.png)

![image](https://user-images.githubusercontent.com/16712383/116524613-29bdbe00-a90a-11eb-8c1c-9b5ee500ec11.png)

**Comment by limingxinleo** [comment]
不支持2.0
